#!/bin/bash

################################
#### CONFIGURACAO DO SISTEMA ####
################################

#Verifica se o usuario e root
	if [ "$(whoami)" != "root" ]; then
		echo "Somente usuario root tem acesso ao script."
		exit 1
	fi

#echo "Atualizando o sistema..."
#	apt-get update

####################################
#### INSTALACAO DOS COMPONENTES ####
####################################
echo "Instalando dependencias..."
	apt-get install inotify-tools -y
	apt-get install ipset -y

echo "Instalando o analisador de logs (psad)..."
	apt-get install psad -y

echo "Instalando complemento do firewall (fwsnort)..."
	apt-get install fwsnort -y

echo "Instalando gerenciador de emails (postfix)..." 
	apt-get install postfix mailutils libsasl2-2 ca-certificates libsasl2-modules-y


######################################
#### CONFIGURACAO DOS COMPONENTES ####
######################################

echo "Configurando postfix..."
	#configurar para o servidor de emails
	postfix reload #reinicializa o postfix

echo "Configurando regras do firewall..."
	./config/iptables/iptables.sh #levanta as regras do firewall

echo "Configurando fwsnort..."
	#cp -r config/fwsnort/snort_rules /etc/fwsnort/
	#executar script de insercao de regras
	fwsnort --update-rules #baixa regras snort do repositorio externo
	fwsnort #converte regras snort para regras do iptables
	/var/lib/fwsnort/fwsnort.sh #salva as regras

echo "Configurando psad..."
	#substituir arquivo de configuracao do psad (incluido no pacote)
	rm /etc/psad/psad.conf
	cp config/psad/psad.conf /etc/psad/psad.conf
	echo "Reinicializando psad..."
	service psad restart

