#!/bin/bash

################################
#### CONFIGURACAO DO SISTEMA ####
################################

#Verifica se o usuario e root
	if [ "$(whoami)" != "root" ]; then
		echo "Somente usuario root tem acesso ao script."
		exit 1
	fi

#echo "Atualizando o sistema..."
#	apt-get update

####################################
#### INSTALACAO DOS COMPONENTES ####
####################################

#echo "Instalando o analisador de logs (psad)..."
#	apt-get install psad -y

#echo "Instalando complemento do firewall (fwsnort)..."
#	apt-get install fwsnort -y

#echo "Instalando gerenciador de emails (postfix)..." 
#	apt-get install postfix mailutils libsasl2-2 ca-certificates libsasl2-modules-y


######################################
#### CONFIGURACAO DOS COMPONENTES ####
######################################

echo "Configurando postfix..."
	#copiar arquivo de configuracao (incluir no pacote)
	#congigurar para gmail (atencao para a senha!)
	#configurar para nao aparecer a tela
	postfix reload #reinicializa o postfix

echo "Configurando regras do firewall..."
	./config/iptables/iptables.sh  #incluir no pacote

echo "Configurando fwsnort..."
	#copiar regras para a pasta do fwsnort (incluir no pacote)
	#executar script de insercao de regras

echo "Configurando psad..."
	#substituir arquivo de configuracao do psad (incluir no pacote)
	#reinicializar psad

########################################
#### INICIALIZACAO DO UPDATE_DAEMON ####
########################################

echo "Inicializando o update_daemon..."
	./update_daemon/auto_block_daemon


